services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: happy!2dothat
      MYSQL_DATABASE: giftsdb
      MYSQL_USER: 'joeuser'
      MYSQL_PASSWORD: 'jopassword'
    ports:
      - "3306:3306"

